name: exui
description: "Build your UI faster. No boilerplate, no dependencies—just powerful widget extensions."
version: 0.0.20
homepage: https://github.com/jozzdart/exui
repository: https://github.com/jozzdart/exui
issue_tracker: https://github.com/jozzdart/exui/issues
topics:
  - flutter
  - widget
  - extension
  - ui
  - widgets

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
